image: jbbgameich/debos-docker

stages:
  - build

halium-default-armhf:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: halium
    VARIANT: default
    ARCH: armhf
  tags:
    - qemu

halium-default-arm64:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: halium
    VARIANT: default
    ARCH: arm64
  tags:
    - qemu

halium-default-i386:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: halium
    VARIANT: default
    ARCH: i386
  tags:
    - qemu

mainline-default-armhf:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: mainline
    VARIANT: default
    ARCH: armhf
  tags:
    - qemu

mainline-default-arm64:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: mainline
    VARIANT: default
    ARCH: arm64
  tags:
    - qemu

mainline-default-i386:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: mainline
    VARIANT: default
    ARCH: i386
  tags:
    - qemu

halium-plamo-armhf:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: halium
    VARIANT: plamo
    ARCH: armhf
  tags:
    - qemu

halium-plamo-arm64:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: halium
    VARIANT: plamo
    ARCH: arm64

halium-plamo-i386:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: halium
    VARIANT: plamo
    ARCH: i386
  tags:
    - qemu

mainline-plamo-armhf:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: mainline
    VARIANT: plamo
    ARCH: armhf
  tags:
    - qemu

mainline-plamo-arm64:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: mainline
    VARIANT: plamo
    ARCH: arm64
  tags:
    - qemu

mainline-plamo-i386:
  stage: build
  script:
    - debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml
  variables:
    RECIPE: mainline
    VARIANT: plamo
    ARCH: i386
  tags:
    - qemu
