sudo: required

# Only build if there's no tag, but manually set the 'continuous' tag for deploy
if: tag IS blank
env:
  global:
    - TRAVIS_TAG=continuous

matrix:
  include:
    - env: ARCH=armhf VARIANT=default RECIPE=halium-generic
    - env: ARCH=arm64 VARIANT=default RECIPE=halium-generic
    - env: ARCH=i386 VARIANT=default RECIPE=halium-generic
    - env: ARCH=armhf VARIANT=default RECIPE=mainline
    - env: ARCH=arm64 VARIANT=default RECIPE=mainline
    - env: ARCH=i386 VARIANT=default RECIPE=mainline

install:
  - echo "deb http://de.archive.ubuntu.com/ubuntu xenial main universe" |sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install dpkg apt debian-archive-keyring -y
  - echo "deb http://deb.debian.org/debian testing main" |sudo tee -a /etc/apt/sources.list
  - sudo apt update
  - sudo apt install debos -y

script:
  - sudo debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml

before_deploy:
    # Set up git user name and tag this commit
  - git config --local user.name "JBBgameich"
  - git config --local user.email "JBBgameich@users.noreply.github.com"
  - git tag -fa "continuous" -m "Generated by Travis-CI"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AKHBWjEqKenes6UN2x3Dtq145tPfkeq4k5nxDW2BdPFB7gTnc180iQX3Qnjf8SO1csWh6Ir3+Wl86HuBxkvI+x/KLL/TGQdDDveza3bD57y8eD+i8gW2Ivny/DQJ2EWfoYP6Of4S6Pm2aIPYY2NLJIYCYahgBGhYh2Ek7GNuTQC1rQrCG5p8QGt3tD64vvo9I9BsJJ44UL5VK2lCL4dEngoFpj4d6Rh+DX9sGEEnwTqRSaLRdx7tAYkcPVQ8uKNHvnzCEIHFZdbQiMF4kl5x8b1NZpOm9N4Uc3haIWRdX0IIt8r+whwEA2yNEOasLquoBRu1v6jtUPkMBqhd1nn9keINmFGGDtEif9s0kkysjknrTgLuPEAmRVvhLFdq41JTyHfaSZs23ScjSLDrfeeJC9hhdsRg38XGW5KIhxh8nHa3UAgVnvlh7Zq/tIyLJ2ZWMZ5UUQtZUY8iKBcG1+fAKuNVFQLp79WNWA1ez8E1Pgscak2qoYCCDwlW9Cbwl/t8SbmMuOhxw6y6A3IBBSRVZfHd8w2SYv2f0vLCNL3a6HTyFTXuPeN+k+WL2zmSgaEn6VmCngTjkaj9flMTyXDYyMYqRxloIwPYVmCaxcf9UNZWiVt+EMuVvXDfLoMvrs7H6rg12jx5pu3K++u5E5p34VK/F6qB6iubSBNzDoygrmY=
  file: 
    - debian-halium-default-buster-armhf.tgz
    - debian-halium-default-buster-arm64.tgz
    - debian-halium-default-buster-i386.tgz
    - debian-mainline-default-buster-armhf.tgz
    - debian-mainline-default-buster-arm64.tgz
    - debian-mainline-default-buster-i386.tgz
  on:
    repo: debian-pm-tools/rootfs-builder-debos
    branch: master
  overwrite: true
