sudo: required
dist: xenial

# Only build if there's no tag, but manually set the 'continuous' tag for deploy
if: tag IS blank
env:
  global:
    - TRAVIS_TAG=continuous

matrix:
  include:
    # command line only images
    - env: ARCH=armhf VARIANT=default RECIPE=halium
    - env: ARCH=arm64 VARIANT=default RECIPE=halium
    - env: ARCH=i386 VARIANT=default RECIPE=halium
    - env: ARCH=armhf VARIANT=default RECIPE=mainline
    - env: ARCH=arm64 VARIANT=default RECIPE=mainline
    - env: ARCH=i386 VARIANT=default RECIPE=mainline
    # Plasma Mobile images
    - env: ARCH=armhf VARIANT=plamo RECIPE=halium
    - env: ARCH=arm64 VARIANT=plamo RECIPE=halium
    - env: ARCH=i386 VARIANT=plamo RECIPE=halium
    - env: ARCH=armhf VARIANT=plamo RECIPE=mainline
    - env: ARCH=arm64 VARIANT=plamo RECIPE=mainline
    - env: ARCH=i386 VARIANT=plamo RECIPE=mainline

install:
  - sudo mkdir -p /usr/etc/default/
  - sudo touch /usr/etc/default/keyboard.default
  - echo "deb http://de.archive.ubuntu.com/ubuntu xenial main universe" |sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install dpkg debian-archive-keyring -y
  - echo "deb http://deb.debian.org/debian testing main" |sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install debos -y

script:
  - sudo debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml

before_deploy:
    # Set up git user name and tag this commit
  - git config --local user.name "JBBgameich"
  - git config --local user.email "JBBgameich@users.noreply.github.com"
  - git tag -fa "continuous" -m "Generated by Travis-CI"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: U27NTsxI+prE09VlkYXoeVEtcJDsNAzU21WgQWYLS3Af3LBnvYVl//i6hx9H6QGYN0ZAoV58YXnieUSKCEEon3PuN7I2U85jyH/qljkO1kM+EdZwhUrLXYyH6L2IooJUk74dxzwb07MTwYWeM6MrWfsxYd2GOYZVf5cTt3MxYiGPiiLugKl6nZCJwLQD2bioKdDxwmdrlGcUyCqWRiX43apalFPsBjZOintB9EACDh2LQNPUfi07t3mBhDOCDb9In+M9PfVJ9TmtpwY8pLfY6ownovJZsWpj8nH0jEQ5c/Zp1k3qaGYElcO55moErz9+dmKhbgMmHKHMP/Z+CEkxWVDZcoJYK4MS/PRhCkf1JzGeHRTGDyocAiMoe+24XztHsBqZH0N0kzT2CwYkER5XrqqR9/50wv3cUhzH7ZZOva+GFvr++ek7erh9nx+3GOsEr42G0k5VlUSDsrgRc37tc6NfLiKW6oYLTwjyDGcwnPADzkChQgEdbtUfSUGYhhhTzhPGyaQ3jiWSfdnH0kUDPxEoF0mqFIvywGXpC9jfZORbvJB2J9F0JhERovSXCJX1MwFqYcj5AqQDMJOw2pf1hJ+/dARR3Ym8sKyfz9N0ScJlxFkp4gKb/AqSIanit/032ZohwDESwfXI2+yXbh+qwsiZhv7+4oQw/++lV9WFscE=
  file: 
    - debian-halium-default-buster-armhf.tgz
    - debian-halium-default-buster-arm64.tgz
    - debian-halium-default-buster-i386.tgz
    - debian-mainline-default-buster-armhf.tgz
    - debian-mainline-default-buster-arm64.tgz
    - debian-mainline-default-buster-i386.tgz
  on:
    repo: debian-pm-tools/rootfs-builder-debos
    branch: master
  overwrite: true
